"""Generate coverage from explicit field evidence, never organization counts alone."""
import json,pathlib,collections
j=json.load(open('data/india.json'));assets={a['id']:a for a in json.load(open('data/media.json'))};sources={s['id']:s for s in j['sources']};rows=[]
commands=[o for o in j['organizations'] if o['level'] in ['command','directorate']]
rows += ['# Data coverage review — 12 September 2026','','This report describes a sourced snapshot and its remaining gaps, not a complete or live order of battle. Manual field review and structural validation serve different purposes. The user authorized implementation on 7 September 2026. Remaining factual gaps are explicit; publication requires implementation verification.','','## Field coverage','','- Service commands: 17 documented commands plus the tri-service Andaman and Nicobar Command. Names, headquarters cities and service relationships manually cross-checked.','- NCC: 17 documented combined/state directorates, plus 2 approved creations. Existing headquarters cities checked against the 2025 DGNCC circular; new directorates remain unmapped.',f'- Leadership: {sum(bool(o.get("commander")) for o in commands)} records with dated or explicitly undated evidence; {sum(not o.get("commander") for o in commands)} command/directorate identities or appointments remain unresolved.','- Portraits: '+str(len(assets))+' identified command-leader photographs with source and reproduction attribution. The remaining records must not silently use a different officer.','- Subordinate formations: existing corps/division associations are explicitly marked as uncorroborated current relationships. Breadth does not establish completeness.','','## Command and directorate matrix','','Dates below describe evidence; they are not a guarantee of present incumbency. An undated profile has an observation date, not an appointment date.','','| Organization | HQ city / evidence | Leader / evidence | Assumed office | Portrait |','|---|---|---|---|---|']
for o in commands:
 c=o.get('commander',{});ev=o['evidence']['headquarters'];loc=(o.get('location') or {}).get('name','Unmapped');hq=loc+' — '+ev['status'];s=sources.get(c.get('sourceIds',[''])[0],{}) if c else {};lead=f"[{c.get('name')}]({s.get('url')}) · {c.get('evidenceKind')} · {c.get('asOf')}" if c else 'Unresolved / not operationally verified';a=assets.get(c.get('portraitId'));photo=f"[Verified official photo]({a['sourceUrl']})" if a else 'Unavailable / verification pending';rows.append(f"| {o['service']} / {o['name']} | {hq} | {lead} | {c.get('assumedOffice','Not verified')} | {photo} |")
rows += ['','## Evidence basis','','[NCC service handbook](https://ncc.kerala.gov.in/images/pdf/handbook/air-foce_jr/AF%20JD%20JW%20WEB%20FINAL%2017%20OCT%202025.pdf), printed pp. 4, 7 and 10, establishes the Army, Navy and Air Force command names and headquarters. Each row was manually compared. Leadership is sourced separately to avoid using old names from general organizational references.','','[DGNCC March 2025 recruitment circular, Appendix A](https://ncemp.in/recruitment/info/uk/esm_hiring_qr.pdf) establishes the 17 directorate names and administrative city locations. This is a public DGNCC document hosted on a third-party mirror; the provenance is explicit. [June 2026 approval](https://www.pib.gov.in/PressReleasePage.aspx?PRID=2272881) establishes the announced AP and Jharkhand directorates, not their operational headquarters.','','## Corrections applied','','- Added Andaman and Nicobar Command as tri-service. Navy is a browsing category, not its chain of command.','- Restored combined AP–Telangana and Bihar–Jharkhand entries during the documented transition; preserved existing shared-link IDs.','- Replaced stale service-command leadership with dated evidence. Kept conflicting NCC names unresolved.','- Removed four permanent fleet-parent claims inferred from a 2025 exercise. Those ships remain unlocated Navy assets.','- Added field evidence, separate assumption dates, portrait attribution, image focal points and explicit verification gaps.','','## Remaining data work','','- Resolve remaining leader identities and assumption dates where reliable evidence exists.','- Complete portrait searches and visual/license checks. Kerala’s identified website portrait explicitly requires permission; it is not included in public assets.','- Corroborate current corps/division parents and expand subordinate coverage. Existing uncertain relationships must be displayed as reported associations, not current command facts.','- Source authentic formation insignia and published geographic coverage. Do not derive territorial polygons from headquarters points.','- Karnataka & Goa: six groups and 55 unit records, including two explicitly historical-only records. Current parent/HQ and leadership coverage remains partial. See ncc-karnataka-goa-audit.md.', '- NCC administrative regions: 17 mapped directorate remits use separately sourced SOI ABDB state geometry; operational transitions remain explicit.','','## Record-specific gaps','']
for o in commands:
 if o.get('verificationGaps'):rows.append('### '+o['name']+' ('+o['service']+')\n\n'+'\n'.join('- '+g for g in o['verificationGaps'])+'\n')
pathlib.Path('docs/data-coverage.md').write_text('\n'.join(rows).rstrip()+'\n');print('Coverage report generated from',len(commands),'reviewed command/directorate entries')
