import { useEffect, useRef } from 'react';
import { X } from 'lucide-react';
export default function AboutDialog({ onClose }: { onClose: () => void }) {
  const ref = useRef<HTMLDialogElement>(null);
  useEffect(() => {
    ref.current?.showModal();
  }, []);
  return (
    <dialog
      ref={ref}
      className="about-panel floating-panel"
      aria-labelledby="about-title"
      onCancel={onClose}
    >
      <header>
        <h2 id="about-title">Reading the atlas</h2>
        <button
          className="icon-button"
          aria-label="Close about"
          autoFocus
          onClick={() => onClose()}
        >
          <X />
        </button>
      </header>
      <p>
        A sourced snapshot of publicly documented organizations. Headquarters
        are approximate city centers. Ships are organizational assets without
        positions.
      </p>
      <h3>Symbols and geography</h3>
      <p>
        Commands use geographic names. Corps and divisions use APP-6-style
        symbols generated by milsymbol: XXX for corps, XX for division, with a
        headquarters staff. Interior function symbols appear only when supported
        by the record.
      </p>
      <p>
        These are presentation conventions, not NATO affiliation. Command
        territory is never inferred from headquarters. The Survey of India
        overview replaces competing administrative border and region-label
        layers.
      </p>
      <h3>Evidence and gaps</h3>
      <p>
        Leadership records show evidence or appointment dates, not live status.
        Some subordinate relationships remain uncorroborated. Open Sources &
        verification in a dossier for the record’s limitations and image
        attribution.
      </p>
      <a href="/data-coverage.md" target="_blank" rel="noreferrer">
        Read the coverage report ↗
      </a>
      <p>
        <a href="/ncc-karnataka-goa-audit.md" target="_blank" rel="noreferrer">
          Karnataka &amp; Goa NCC: group and unit research ↗
        </a>
      </p>
    </dialog>
  );
}
