import { useEffect, useRef } from 'react';
import { X } from 'lucide-react';
export default function AboutDialog({ onClose }: { onClose: () => void }) {
  const ref = useRef<HTMLDialogElement>(null);
  useEffect(() => {
    ref.current?.showModal();
  }, []);
  return (
    <dialog
      ref={ref}
      className="about-panel floating-panel"
      aria-labelledby="about-title"
      onCancel={onClose}
    >
      <header>
        <h2 id="about-title">Reading the atlas</h2>
        <button
          className="icon-button"
          aria-label="Close about"
          autoFocus
          onClick={() => onClose()}
        >
          <X />
        </button>
      </header>
      <p>
        A sourced snapshot of publicly documented organizations. Headquarters
        are approximate city centers. Ships are organizational assets without
        positions.
      </p>
      <h3>Symbols and geography</h3>
      <p>
        Commands use geographic names. Corps and divisions use APP-6-style
        symbols generated by milsymbol: XXX for corps, XX for division, with a
        headquarters staff. Interior function symbols appear only when supported
        by the record.
      </p>
      <p>
        These are presentation conventions, not NATO affiliation. Command
        territory is never inferred from headquarters. The Survey of India
        overview replaces competing administrative border and region-label
        layers for India. Pakistan uses Natural Earth’s de facto boundary
        convention, including disputed territories; it does not represent a
        position on sovereignty. China uses a Natural Earth overview with Survey
        of India Ladakh and Arunachal Pradesh overlap excluded. Organizational
        affiliation is separate from territorial presentation.
      </p>
      <p>
        China’s joint theaters are browsed in Army mode. Linked service
        components retain their separate administrative parents. PLA group
        armies use corps-level symbols.
      </p>
      <h3>Evidence and gaps</h3>
      <p>
        The version-controlled dataset retains dated leadership records,
        field-level evidence and unresolved research gaps.
      </p>
      <p>
        <a href="/image-credits.html" target="_blank" rel="noreferrer">
          Portrait credits and reuse attribution ↗
        </a>
      </p>
      <a href="/data-coverage.md" target="_blank" rel="noreferrer">
        Read the coverage report ↗
      </a>
      <p>
        <a href="/navy-airforce-audit.md" target="_blank" rel="noreferrer">
          Navy &amp; Air Force: ships, bases and squadrons ↗
        </a>
      </p>
      <p>
        <a href="/china-audit.md" target="_blank" rel="noreferrer">
          China: evidence, leadership gaps and geography ↗
        </a>
      </p>
      <p>
        <a href="/pakistan-audit.md" target="_blank" rel="noreferrer">
          Pakistan: coverage and unresolved fields ↗
        </a>
      </p>
      <p>
        <a href="/ncc-reorganization.md" target="_blank" rel="noreferrer">
          NCC: the 19-directorate transition ↗
        </a>
      </p>
      <p>
        <a href="/ncc-karnataka-goa-audit.md" target="_blank" rel="noreferrer">
          Karnataka &amp; Goa NCC: group and unit research ↗
        </a>
      </p>
    </dialog>
  );
}
